// Even Fibonacci numbers
// https://projecteuler.net/problem=2

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

function fib(n) {
  let result = [1];
  let i = 1, newVal = 2;
  while (newVal < n) {
    result.push(newVal);
    i++;
    newVal = result[i - 1] + result[i - 2]
  }  
  return result;
}

function sumEvens() {
  return (fib(4000000).reduce((acc, val) => {
    if (val % 2 === 0) {
      return acc + val;
    } else {
      return acc;
    }
  }, 0))
}

console.log(sumEvens());